import "./globals.css";
import type { Metadata } from "next";
import { Bellota_Text } from "next/font/google";

const bellota_Text = Bellota_Text({
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dental Clinic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${bellota_Text.className} bg-pricolor`}>
        {children}
      </body>
    </html>
  );
}
